//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net14Web.LocalizationFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Booking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Booking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net14Web.LocalizationFiles.Booking", typeof(Booking).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingWeb.
        /// </summary>
        public static string LayoutBooking {
            get {
                return ResourceManager.GetString("LayoutBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car rentals.
        /// </summary>
        public static string NavbarCarRentals {
            get {
                return ResourceManager.GetString("NavbarCarRentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        public static string NavbarFlights {
            get {
                return ResourceManager.GetString("NavbarFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My searches.
        /// </summary>
        public static string NavbarMySearches {
            get {
                return ResourceManager.GetString("NavbarMySearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stays.
        /// </summary>
        public static string NavbarStays {
            get {
                return ResourceManager.GetString("NavbarStays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserChat.
        /// </summary>
        public static string NavbarUserChat {
            get {
                return ResourceManager.GetString("NavbarUserChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin.
        /// </summary>
        public static string SearchCheckin {
            get {
                return ResourceManager.GetString("SearchCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string SearchCheckout {
            get {
                return ResourceManager.GetString("SearchCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string SearchCity {
            get {
                return ResourceManager.GetString("SearchCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string SearchCountry {
            get {
                return ResourceManager.GetString("SearchCountry", resourceCulture);
            }
        }
    }
}
