//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet14Web.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RealEstate_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RealEstate_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RealEstateNet14Web.Localization.RealEstate_en", typeof(RealEstate_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SearchForRealEstateInMinsk {
            get {
                return ResourceManager.GetString("SearchForRealEstateInMinsk", resourceCulture);
            }
        }
        
        internal static string Assistent {
            get {
                return ResourceManager.GetString("Assistent", resourceCulture);
            }
        }
        
        internal static string ICanHelpYou_ {
            get {
                return ResourceManager.GetString("ICanHelpYou?", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string AddAnnouncement {
            get {
                return ResourceManager.GetString("AddAnnouncement", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string AllAnnouncement {
            get {
                return ResourceManager.GetString("AllAnnouncement", resourceCulture);
            }
        }
        
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        internal static string Apartament {
            get {
                return ResourceManager.GetString("Apartament", resourceCulture);
            }
        }
        
        internal static string Garages {
            get {
                return ResourceManager.GetString("Garages", resourceCulture);
            }
        }
        
        internal static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        internal static string ForALongTime {
            get {
                return ResourceManager.GetString("ForALongTime", resourceCulture);
            }
        }
        
        internal static string ForADay {
            get {
                return ResourceManager.GetString("ForADay", resourceCulture);
            }
        }
        
        internal static string NewBuildings {
            get {
                return ResourceManager.GetString("NewBuildings", resourceCulture);
            }
        }
        
        internal static string ResidentialComplexes {
            get {
                return ResourceManager.GetString("ResidentialComplexes", resourceCulture);
            }
        }
        
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        internal static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        internal static string HowManyRooms_ {
            get {
                return ResourceManager.GetString("HowManyRooms?", resourceCulture);
            }
        }
        
        internal static string AtWhatCost_ {
            get {
                return ResourceManager.GetString("AtWhatCost?", resourceCulture);
            }
        }
        
        internal static string InWhatCity_ {
            get {
                return ResourceManager.GetString("InWhatCity?", resourceCulture);
            }
        }
    }
}
